name: Push To Windows VM
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Extract build artifact
        shell: powershell
        run: |
          tar -xzf 'C:\Windows\System32\actions-runner\actions-runner\_work\CampusConnectBuild\CampusConnectBuild\76045f96-54b9-47b9-a861-c7df460861e0.tar.gz' `
              -C 'C:\Windows\System32\actions-runner\actions-runner\_work\CampusConnectBuild\CampusConnectBuild\'

      - name: Copy to host directory
        shell: powershell
        run: |
          Copy-Item `
            -Path 'C:\Windows\System32\actions-runner\actions-runner\_work\CampusConnectBuild\CampusConnectBuild\*' `
            -Destination 'C:\inetpub\wwwroot' `
            -Recurse `
            -Force
